### ISSUE TITLE
Weird startup error about NAs

### ISSUE THREAD

**Issue by jabbate7** [CRPE-UWB/osr_dssg2018#28]
On startup, I get the following message in the console, with the issue bolded: 

Listening on http://127.0.0.1:5333
OGR data source with driver: ESRI Shapefile 
Source: "/Users/josephabbate/Documents/Experiences/Applications/UWashington/Project/osr_dssg2018/data/nbhd_dem_shapes", layer: "nbhd_dem_shapes"
with 78 features
It has 12 fields
**Warning in eval(ei, envir) : NAs introduced by coercion
Warning in eval(ei, envir) : NAs introduced by coercion**

**Comment by kelliemac** [comment]
caused by people typing in non-number to mincost, maxcost, minage, maxage in the googleanalytics data

**Comment by kelliemac** [comment]
@jabbate7 fixed it!!!!!
