### ISSUE TITLE
Empty Selection not currently possible

### ISSUE THREAD

**Issue by jabbate7** [CRPE-UWB/osr_dssg2018#29]
For example, set min and max cost to be $760. No programs cost $760, so in place of a map we get:

**Error: invalid 'type' (list) of argument**

**Comment by kelliemac** [comment]
we should have a special case in add_circle_markers for when the dataframe input is empty

**Comment by kelliemac** [comment]
@jabbate7 i fixed this (i think) - you should take a look and see if you notice any issues!
