### ISSUE TITLE
finish "manual" tab with instructions on how to use dashboard

### ISSUE THREAD

**Issue by kelliemac** [CRPE-UWB/osr_dssg2018#49]
add "manual" tab with instructions on how to use dashboard

**Comment by kelliemac** [comment]
as per reschool comments: needs to explain 
1) what the access index is
2) what the "% students using transportation" is

**Comment by jabbate7** [comment]
Outline: https://docs.google.com/document/d/1s7th6_XcywOcDcLKwEPfl0j-RWXsf3jxhGe1qlD4oFU/edit
